version: '3.8'
services:
  app:
    image: dattahub
    build:
      context: ./
      target: dev
      dockerfile: dev.Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"