version: '3.8'
services:
  app:
    image: dattahub
    container_name: dattahub
    restart: always
    build:
      context: ./
      dockerfile: prod.Dockerfile
      target: production
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"
    networks:
      - web_network
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - 80:3000
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./staticfiles/:/app/static/
        #- media_volume:/app/media/:ro
    networks:
      - web_network
    depends_on:
      - app
      - certbot
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 